spring:
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{엔드포인트}:3306/myselectshop #jdbc:h2:tcp://localhost/~/testdb
    username: admin
    level:
    password:


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  logging:
      org.hibernate.SQL: debug
      org.hibernate.type: trace

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    serialization:
      fail-on-empty-beans: false

jwt:
  secret:
    key: 7J2064W467Kg7J207IWY7Lqg7ZSE7IiY6rCV7IOd67aE65Ok7ZmU7J207YyF7ZWY7IS47JqU7KKL7J2A7ZqM7IKs7JeQ66qo65GQ7Leo7JeF7ISx6rO17ZWY7Iuk6rGw652866+/7Iq164uI64uk65287J2067iM7IS47IWY65Ok7Ja07KO87IWU7ISc6rCQ7IKs7ZWp64uI64uk64+E7JuA7J2065CY7JeI7Jy866m07KKL6rKg7Iq164uI64uk

server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
kapt:
  incremental:
    apt=true